# Generated by Django 3.2.9 on 2021-12-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_driver_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
